### ISSUE TITLE
Comparation between RotationNet and MVCNN

### ISSUE THREAD

**Issue by XHQvi** [RBirkeland/MVCNN-PyTorch#10]
Thank you for your code.
I noticed that you said your RotationNet implement outperforms MVCNN. But I did some experiments about these two models, and found that RotationNet only performs better on some specific dataset. All datasets I used is rendered from ModelNet40 with different render settings. 
I didn't use your implement in these experiments. So could you share your experiment result?
Thank you.

**Comment by RBirkeland** [comment]
Hi, I don't have some specific numbers to share. But during testing I found that RotationNet only outperformed MVCNN in more complex datasets (number of classes, complexity of data to model). So in simpler cases MVCNN would perform just as good. However, if I remember correctly RotationNet was much faster at test time.
