### ISSUE TITLE
Accuracy and Save Model

### ISSUE THREAD

**Issue by albertotono** [RBirkeland/MVCNN-PyTorch#14]
Dear @RBirkeland, 
I tested your model and it gave me these results

```
        Iter [2460/2461] Loss: 0.5472
Time taken: 417.52 sec.

Evaluation:
        Val Acc: 71.72 - Loss: 1.0213
        Current best val acc: 0.00
```

I was wondering: 

1. How can I test this model with random images? 
2. If I don't use the logger.py, is there a way I can still save the model? 

Thank you

**Comment by RBirkeland** [comment]
1. Yes you can create your own dataset by creating a dataset of 3D objects and convert the 3D objects to 2D images. Please read the readme file for details.
2. The model is automatically saved whenever the accuracy is improving.
